"use client";

import { useMemo, useState, type ReactNode } from "react";
import Link from "next/link";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { Select } from "@/shared/ui/select";
import { useAuth } from "@/modules/auth/auth-provider";
import { useWorkspace } from "@/modules/workspace/workspace-provider";
import { worldApi, type WorldApiContext } from "./api";
import { canNarrowPermissions, createOperationKey, hasPermissionChanges, limitedChangeWorldCode, worldQueryKeys } from "./state";
import type { WorldInstance, WorldPermissions, WorldStatus, WorldVisibility } from "./types";
import { WorldErrorNotice, WorldPageHeader } from "./ui";

const permissionLabels: Record<keyof WorldPermissions, string> = { ordinary_relationship: "普通关系变化", intimate_relationship: "亲密关系变化", minor_injury: "轻微受伤", long_term_memory: "形成长期记忆", appearance_adaptation: "外观适应" };
const healthLabels: Record<string, string> = { running: "运行正常", paused: "世界已暂停", archived: "世界已归档", blocked: "运行受阻", takedown: "公开投影已下架", model_unavailable: "模型暂时不可用，服务会按策略恢复", content_idle: "暂时没有形成有效变化", projection_lag: "记忆投影稍有延迟，当前不会使用降级上下文" };

function useCtx(): WorldApiContext { const { session } = useAuth(); const { workspaceCode } = useWorkspace(); return { apiKey: session?.apiKey || "", workspaceCode }; }
function Panel({ title, children, busy, error, retry }: { title: string; children: ReactNode; busy?: boolean; error?: unknown; retry?: () => void }) { return <section className="panel min-w-0 p-5" aria-busy={busy || undefined}><h2 className="text-lg font-semibold">{title}</h2>{busy && <p role="status" className="mt-3 text-sm text-text-muted">正在加载真实数据…</p>}{Boolean(error) && <div className="mt-3"><WorldErrorNotice error={error} onRetry={retry} /></div>}{children}</section>; }

export function WorldRuntimeConsole({ worldCode, worldStatus, role }: { worldCode: string; worldStatus: WorldStatus; role: string }) {
  const ctx = useCtx(); const client = useQueryClient(); const enabled = Boolean(ctx.apiKey && worldCode);
  const projection = useQuery({ queryKey: worldQueryKeys.projection(ctx.workspaceCode, worldCode), queryFn: () => worldApi.projection(ctx, worldCode), enabled: enabled && !["draft", "published"].includes(worldStatus) });
  const contract = useQuery({ queryKey: worldQueryKeys.runtimeContract(ctx.workspaceCode, worldCode), queryFn: () => worldApi.runtimeContract(ctx, worldCode), enabled: enabled && worldStatus !== "draft" });
  const recaps = useQuery({ queryKey: worldQueryKeys.recaps(ctx.workspaceCode, worldCode), queryFn: () => worldApi.publicRecaps(ctx, worldCode), enabled: enabled && !["draft", "published"].includes(worldStatus) });
  const isOwner = role === "owner" || role === "world_owner";
  const reviews = useQuery({ queryKey: worldQueryKeys.reviews(ctx.workspaceCode, worldCode), queryFn: () => worldApi.reviewSubmissions(ctx, worldCode), enabled: enabled && isOwner });
  const reports = useQuery({ queryKey: worldQueryKeys.reports(ctx.workspaceCode, worldCode), queryFn: () => worldApi.ownerReports(ctx, worldCode), enabled: enabled && isOwner });
  const fence = useQuery<WorldInstance>({ queryKey: worldQueryKeys.runtimeFence(ctx.workspaceCode, worldCode), queryFn: async () => { throw new Error("runtime command identity is write-derived"); }, enabled: false });
  const [action, setAction] = useState<"pause" | "resume" | "archive">(worldStatus === "paused" ? "resume" : "pause"); const [barrierBusy, setBarrierBusy] = useState(false); const [barrierError, setBarrierError] = useState<unknown>();
  const actorProjection = projection.data; const timeline = actorProjection && "timeline" in actorProjection ? actorProjection.timeline : [];
  const residents = actorProjection && "public_residents" in actorProjection ? actorProjection.public_residents : actorProjection && "owned_participant" in actorProjection ? [actorProjection.owned_participant] : [];
  async function applyBarrier() { if (!fence.data || barrierBusy) return; if ((action === "archive" || action === "pause") && !window.confirm(action === "archive" ? "归档会停止新行动并保留合规历史，且不可作为删除。确认归档？" : "暂停会取消未提交行动并保留历史。确认暂停？")) return; setBarrierBusy(true); setBarrierError(undefined); try { const next = await worldApi.barrier(ctx, worldCode, action, { run_epoch: fence.data.run_epoch, fencing_token: fence.data.fencing_token, expected_revision: fence.data.state_revision }); client.setQueryData(worldQueryKeys.runtimeFence(ctx.workspaceCode, worldCode), { ...fence.data, ...next, status: action === "resume" ? "running" : action === "archive" ? "archived" : "paused" }); await Promise.all([projection.refetch(), client.invalidateQueries({ queryKey: worldQueryKeys.detail(ctx.workspaceCode, worldCode) })]); } catch (error) { setBarrierError(error); await projection.refetch(); } finally { setBarrierBusy(false); } }
  return <div className="mt-5 grid w-full min-w-0 gap-4 lg:grid-cols-2">
    <Panel title="运行状态与异常" busy={projection.isLoading} error={projection.error} retry={() => void projection.refetch()}><p className="mt-3 text-sm">{actorProjection && "runtime_health" in actorProjection ? healthLabels[actorProjection.runtime_health] || `服务状态：${actorProjection.runtime_health}` : worldStatus === "published" ? "世界尚未 bootstrap。" : "等待运行投影。"}</p>{projection.isFetching && projection.data && <p role="status" className="mt-2 text-xs text-text-muted">正在后台更新，当前显示上次真源。</p>}<div className="mt-4 grid min-w-0 gap-2 sm:grid-cols-2">{residents.map((resident) => <article key={resident.participant_code} className="min-w-0 rounded-lg border border-border p-3"><strong className="break-words">{resident.public_identity}</strong><p className="break-words text-sm text-text-muted">{resident.status}</p><Link className="mt-2 flex min-h-11 items-center break-words text-sm text-primary" href={`/world-agent-owner/participants/${resident.participant_code}`}>Agent Owner 控制</Link></article>)}</div></Panel>
    <Panel title="预算与运行策略" busy={contract.isLoading} error={contract.error} retry={() => void contract.refetch()}>{contract.data && <div className="mt-3 space-y-2 text-sm"><p>服务策略上限（不是前端推算的使用量）</p><p>单次：输入 {contract.data.budget.call.input_tokens} / 输出 {contract.data.budget.call.output_tokens} tokens，{contract.data.budget.call.timeout_seconds}s</p><p>每 Tick：模型 {contract.data.budget.tick.llm_calls} 次、候选 {contract.data.budget.tick.candidates}、提交 {contract.data.budget.tick.commits}</p><p>业务日：模型尝试 {contract.data.budget.business_day.model_attempts}，保留回顾 {contract.data.budget.business_day.reserved_rev1_attempts}</p><p>回顾：{contract.data.review_policy.generate_at}，最多 {contract.data.review_policy.max_revisions} 个修订</p></div>}</Panel>
    <Panel title="已提交时间线" busy={projection.isLoading} error={projection.error} retry={() => void projection.refetch()}>{!projection.isLoading && !projection.error && timeline.length === 0 && <p className="mt-3 text-sm text-text-muted">还没有已提交事件。</p>}<ol className="mt-3 space-y-3">{timeline.map((event) => <li key={event.event_code} className="rounded-lg border border-border p-3"><div className="flex flex-wrap justify-between gap-2"><strong>{event.event_type} · {event.semantic_kind}</strong><span className="font-mono text-xs">#{event.event_sequence}</span></div><p className="mt-1 text-sm">{event.summary}</p><p className="mt-1 text-xs text-text-muted">原因：{event.cause_summary}</p><time className="mt-1 block text-xs text-text-muted">{new Date(event.created_at).toLocaleString("zh-CN")}</time></li>)}</ol></Panel>
    <Panel title="每日回顾" busy={recaps.isLoading} error={recaps.error} retry={() => void recaps.refetch()}>{!recaps.isLoading && !recaps.error && (recaps.data?.items.length || 0) === 0 && <p className="mt-3 text-sm text-text-muted">尚无公开回顾；不会生成本地假摘要。</p>}<div className="mt-3 space-y-3">{recaps.data?.items.map((recap) => <article key={recap.recap_code || `${recap.business_date}-${recap.revision}`} className="rounded-lg border border-border p-3"><strong>{recap.business_date} · 修订 {recap.revision} · {recap.status}</strong>{recap.summary && <p className="mt-1 text-sm">{recap.summary}</p>}{recap.status === "pending" && <p className="mt-1 text-sm text-text-muted">回顾正在生成，稍后刷新真源。</p>}{recap.status === "failed" && <p className="mt-1 text-sm text-warning">本次回顾暂不可用，不会由前端补写摘要。</p>}{recap.source_from_sequence !== undefined && recap.source_to_sequence !== undefined && <p className="mt-1 text-xs text-text-muted">事件序列 {recap.source_from_sequence}–{recap.source_to_sequence}</p>}</article>)}</div></Panel>
    <Panel title="暂停、恢复与归档" error={barrierError} retry={() => void projection.refetch()}><p className="mt-3 text-sm text-text-muted">停止命令必须使用服务端实例 epoch/fence/revision。为避免猜测，只有本会话真实 bootstrap 返回命令身份后才可执行。</p><div className="mt-3 flex flex-wrap gap-2"><Select ariaLabel="运行控制动作" value={action} onValueChange={(value) => setAction(value as typeof action)} options={[{ value: "pause", label: "暂停" }, { value: "resume", label: "恢复" }, { value: "archive", label: "归档" }]} /><button type="button" className={action === "archive" ? "button-danger" : "button-secondary"} disabled={!fence.data || barrierBusy} onClick={() => void applyBarrier()}>{barrierBusy ? "正在确认结果…" : "执行运行控制"}</button></div>{!fence.data && <p role="status" className="mt-3 text-sm text-warning">刷新后后端当前没有只读命令身份恢复接口，因此不会发送带猜测 revision 的 barrier。</p>}</Panel>
    <Panel title="审核材料与举报" busy={reviews.isLoading || reports.isLoading} error={reviews.error || reports.error} retry={() => { void reviews.refetch(); void reports.refetch(); }}><p className="mt-3 text-sm">审核材料 {reviews.data?.items.length || 0} 条；举报 {reports.data?.items.length || 0} 条。</p><Link href={`/worlds/${worldCode}/governance`} className="button-secondary mt-3 min-h-11">打开治理材料</Link></Panel>
  </div>;
}

export function WorldGovernanceWorkspace({ worldCode }: { worldCode: string }) {
  const ctx = useCtx(); const client = useQueryClient(); const detail = useQuery({ queryKey: worldQueryKeys.detail(ctx.workspaceCode, worldCode), queryFn: () => worldApi.detail(ctx, worldCode), enabled: Boolean(ctx.apiKey) }); const reviews = useQuery({ queryKey: worldQueryKeys.reviews(ctx.workspaceCode, worldCode), queryFn: () => worldApi.reviewSubmissions(ctx, worldCode), enabled: Boolean(ctx.apiKey) }); const reports = useQuery({ queryKey: worldQueryKeys.reports(ctx.workspaceCode, worldCode), queryFn: () => worldApi.ownerReports(ctx, worldCode), enabled: Boolean(ctx.apiKey) });
  const visibilityKey = useMemo(() => createOperationKey("world-visibility"), []); const reviewKey = useMemo(() => createOperationKey("world-review"), []); const [visibility, setVisibility] = useState<WorldVisibility | "">(""); const [savedVisibility, setSavedVisibility] = useState<{ visibility: WorldVisibility; revision: number }>(); const [summary, setSummary] = useState(""); const [busy, setBusy] = useState(""); const [error, setError] = useState<unknown>();
  async function saveVisibility() { if (!detail.data || !visibility) return; setBusy("visibility"); setError(undefined); try { const next = await worldApi.setVisibility(ctx, worldCode, visibility, detail.data.world.revision, visibilityKey.current()); visibilityKey.reset(); setSavedVisibility(next); await client.invalidateQueries({ queryKey: worldQueryKeys.detail(ctx.workspaceCode, worldCode) }); } catch (next) { setError(next); await detail.refetch(); } finally { setBusy(""); } }
  async function submitReview() { if (!detail.data || !summary.trim()) return; setBusy("review"); setError(undefined); try { await worldApi.submitReview(ctx, worldCode, summary.trim(), detail.data.world.revision, reviewKey.current()); reviewKey.reset(); setSummary(""); await reviews.refetch(); } catch (next) { setError(next); await Promise.all([detail.refetch(), reviews.refetch()]); } finally { setBusy(""); } }
  return <div><WorldPageHeader title="公开状态、审核材料与举报" description="通过真实 owner API 管理公开状态、提交 Creator 审核材料并查看 Owner 可见举报。" back={`/worlds/${worldCode}`} />{Boolean(error) && <WorldErrorNotice error={error} onRetry={() => { void detail.refetch(); void reviews.refetch(); void reports.refetch(); }} />}<div className="grid gap-5 lg:grid-cols-2"><Panel title="公开可见性" busy={detail.isLoading} error={detail.error} retry={() => void detail.refetch()}><p className="mt-3 text-sm text-text-muted">listed 会进入发现；unlisted 仅直链；hidden 关闭公共读取。可见性变化不等于暂停运行。</p>{savedVisibility && <p role="status" className="mt-3 text-sm">服务端已确认：{savedVisibility.visibility}（revision {savedVisibility.revision}）</p>}<div className="mt-4 flex flex-wrap gap-2"><Select ariaLabel="公开可见性" value={visibility} onValueChange={(value) => setVisibility(value as WorldVisibility | "")} options={[{ value: "", label: "请选择目标状态" }, { value: "listed", label: "公开列出" }, { value: "unlisted", label: "仅直链" }, { value: "hidden", label: "隐藏" }]} /><button type="button" className="button-primary" disabled={!detail.data || !visibility || Boolean(busy)} onClick={() => void saveVisibility()}>{busy === "visibility" ? "正在确认…" : "保存可见性"}</button></div></Panel><Panel title="提交审核材料" busy={reviews.isLoading} error={reviews.error} retry={() => void reviews.refetch()}><textarea aria-label="审核材料摘要" maxLength={1000} value={summary} onChange={(event) => setSummary(event.target.value)} className="area mt-3" /><button type="button" className="button-primary mt-3" disabled={!summary.trim() || Boolean(busy)} onClick={() => void submitReview()}>{busy === "review" ? "正在确认…" : "提交材料"}</button><div className="mt-4 space-y-2">{reviews.data?.items.map((item) => <article className="rounded-lg border border-border p-3" key={item.submission_code}><strong>{item.status === "withdrawn" ? "已撤回" : "已提交"}</strong><p className="mt-1 text-sm">{item.material_summary}</p><p className="mt-1 font-mono text-xs">revision {item.revision}</p></article>)}</div></Panel><Panel title="Owner 可见举报" busy={reports.isLoading} error={reports.error} retry={() => void reports.refetch()}><div className="mt-3 space-y-2">{reports.data?.items.map((item) => <article className="rounded-lg border border-border p-3" key={item.report_code}><strong>{item.category} · {item.status}</strong><p className="mt-1 text-sm">{item.summary}</p></article>)}{reports.data?.items.length === 0 && <p className="text-sm text-text-muted">没有可见举报。</p>}</div></Panel></div></div>;
}

function PermissionEditor({ original, value, onChange }: { original: WorldPermissions; value: WorldPermissions; onChange: (next: WorldPermissions) => void }) { return <fieldset className="mt-4"><legend className="font-medium">可收紧权限</legend>{(Object.keys(original) as (keyof WorldPermissions)[]).map((key) => <label key={key} className="mt-2 flex min-h-11 items-center gap-3"><input type="checkbox" checked={value[key]} disabled={!original[key]} onChange={(event) => onChange({ ...value, [key]: event.target.checked })} />{permissionLabels[key]}{!original[key] && <span className="text-xs text-text-muted">未获授，不能放宽</span>}</label>)}</fieldset>; }

export function AgentOwnerBindingWorkspace({ participantCode }: { participantCode: string }) {
  const ctx = useCtx(); const client = useQueryClient(); const query = useQuery({ queryKey: worldQueryKeys.agentOwnerBinding(ctx.workspaceCode, participantCode), queryFn: () => worldApi.agentOwnerBinding(ctx, participantCode), enabled: Boolean(ctx.apiKey) }); const key = useMemo(() => createOperationKey("agent-owner-binding"), []); const recallKey = useMemo(() => createOperationKey("agent-owner-recall"), []); const [permissions, setPermissions] = useState<WorldPermissions>(); const [busy, setBusy] = useState(""); const [error, setError] = useState<unknown>(); const binding = query.data; const current = permissions || binding?.permissions;
  const canSavePermissions = Boolean(binding && current && canNarrowPermissions(binding.permissions, current) && hasPermissionChanges(binding.permissions, current));
  async function narrow() { if (!binding || !current || !canSavePermissions) return; setBusy("permissions"); setError(undefined); try { const next = await worldApi.narrowAgentOwnerPermissions(ctx, participantCode, current, binding.revision, key.current()); key.reset(); client.setQueryData(worldQueryKeys.agentOwnerBinding(ctx.workspaceCode, participantCode), next); setPermissions(next.permissions); } catch (next) { setError(next); await query.refetch(); } finally { setBusy(""); } }
  async function recall() { if (!binding || !window.confirm(`召回“${binding.public_identity}”后不能在同一实例重新加入，历史会保留。确认召回？`)) return; setBusy("recall"); setError(undefined); try { const next = await worldApi.recallAgentOwner(ctx, participantCode, binding.revision, recallKey.current()); recallKey.reset(); client.setQueryData(worldQueryKeys.agentOwnerBinding(ctx.workspaceCode, participantCode), next); } catch (next) { setError(next); await query.refetch(); } finally { setBusy(""); } }
  return <div className="mx-auto max-w-3xl"><WorldPageHeader title="Agent Owner 运行控制" description="只显示当前所有者拥有的 binding；foreign 或失权统一不可枚举。" back={binding ? `/worlds/${binding.world_code}` : "/worlds"} />{Boolean(query.error || error) && <WorldErrorNotice error={query.error || error} onRetry={() => void query.refetch()} />}{query.isLoading && <p role="status">正在读取 binding…</p>}{binding && current && <section className="panel p-6"><strong className="text-xl">{binding.public_identity}</strong><p className="mt-2 font-mono text-xs">{binding.participant_code} · revision {binding.revision}</p><p className="mt-2">状态：{binding.status}</p><PermissionEditor original={binding.permissions} value={current} onChange={setPermissions} /><div className="mt-5 flex flex-wrap gap-3"><button type="button" className="button-primary" disabled={Boolean(busy) || !canSavePermissions} onClick={() => void narrow()}>{busy === "permissions" ? "正在确认…" : "保存收紧权限"}</button><button type="button" className="button-danger" disabled={Boolean(busy) || binding.status !== "active"} onClick={() => void recall()}>{busy === "recall" ? "正在确认…" : binding.status === "active" ? "召回角色" : "角色已离开"}</button></div></section>}</div>;
}

export function AgentOwnerLimitedChangeWorkspace({ changeCode }: { changeCode: string }) {
  const ctx = useCtx(); const client = useQueryClient(); const query = useQuery({ queryKey: worldQueryKeys.limitedChange(ctx.workspaceCode, changeCode), queryFn: () => worldApi.agentOwnerLimitedChange(ctx, changeCode), enabled: Boolean(ctx.apiKey) }); const change = query.data; const binding = useQuery({ queryKey: worldQueryKeys.agentOwnerBinding(ctx.workspaceCode, change?.subject_participant_code || "pending"), queryFn: () => worldApi.agentOwnerBinding(ctx, change!.subject_participant_code), enabled: Boolean(ctx.apiKey && change?.subject_participant_code) }); const worldCode = limitedChangeWorldCode(change, binding.data); const key = useMemo(() => createOperationKey("limited-change"), []); const [selected, setSelected] = useState(""); const [busy, setBusy] = useState(false); const [error, setError] = useState<unknown>();
  async function decide(decision: "choice" | "reject") { if (!change || !worldCode || (decision === "choice" && !selected)) return; setBusy(true); setError(undefined); try { await worldApi.decideLimitedChange(ctx, worldCode, changeCode, { decision, candidate_code: decision === "choice" ? selected : undefined, run_epoch: change.run_epoch, fencing_token: change.fencing_token, expected_revision: change.state_revision, idempotency_key: key.current() }); key.reset(); await client.invalidateQueries({ queryKey: worldQueryKeys.limitedChange(ctx.workspaceCode, changeCode) }); } catch (next) { setError(next); await Promise.all([query.refetch(), binding.refetch()]); } finally { setBusy(false); } }
  return <div className="mx-auto max-w-3xl"><WorldPageHeader title="有限候选确认" description="最多三个由服务端生成的可逆候选；不能编辑补丁或自由输入结果。" back={worldCode ? `/worlds/${worldCode}` : "/worlds"} />{Boolean(query.error || binding.error || error) && <WorldErrorNotice error={query.error || binding.error || error} onRetry={() => { void query.refetch(); if (change) void binding.refetch(); }} />}{(query.isLoading || binding.isLoading) && <p role="status">正在读取候选与所属 binding…</p>}{change && <section className="panel p-6"><p>类型：{change.kind}</p><p className="mt-1 text-sm text-text-muted">状态 {change.status} · revision {change.state_revision}</p><fieldset className="mt-4 space-y-2"><legend className="font-medium">选择一个候选</legend>{change.candidates.map((candidate) => <label className="flex min-h-11 items-center gap-3 rounded-lg border border-border p-3" key={candidate.candidate_code}><input type="radio" name="candidate" checked={selected === candidate.candidate_code} onChange={() => setSelected(candidate.candidate_code)} />{candidate.value} · 可逆 {candidate.reversible_days} 天</label>)}</fieldset>{!worldCode && !binding.isLoading && !binding.error && <p role="alert" className="mt-4 text-sm text-danger">服务端候选与所属 binding 不一致；不会构造 decision route。</p>}<div className="mt-5 flex gap-3"><button type="button" className="button-primary" disabled={busy || !worldCode || !selected || change.status !== "pending"} onClick={() => void decide("choice")}>确认候选</button><button type="button" className="button-secondary" disabled={busy || !worldCode || change.status !== "pending"} onClick={() => void decide("reject")}>拒绝变化</button></div></section>}</div>;
}
