"use client";

import { useRef, useState, type ReactNode } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useQuery } from "@tanstack/react-query";
import { Plus, Sparkle } from "@phosphor-icons/react";
import { useAuth } from "@/modules/auth/auth-provider";
import { useWorkspace } from "@/modules/workspace/workspace-provider";
import { worldApi, type WorldApiContext } from "./api";
import { createEmptyWorldContent, type WorldStatus, type WorldTemplate } from "./types";
import { newIdempotencyKey, worldQueryKeys } from "./state";
import { WorldErrorNotice, WorldPageHeader, WorldStatusBadge } from "./ui";

function useCtx(): { ctx: WorldApiContext; demo: boolean } { const { session, demo } = useAuth(); const { workspaceCode } = useWorkspace(); return { ctx: { apiKey: session?.apiKey || "", workspaceCode }, demo }; }
function useUiError(): [ReactNode | undefined, (value: unknown) => void] { const [value, setValue] = useState<unknown>(); return [value as ReactNode | undefined, setValue]; }
const FILTERS: { value: "" | WorldStatus; label: string }[] = [{ value: "", label: "全部" }, { value: "draft", label: "草稿" }, { value: "published", label: "待开演" }, { value: "running", label: "运行中" }, { value: "paused", label: "已暂停" }, { value: "archived", label: "已归档" }];

export function WorldsWorkspace() {
  const { ctx, demo } = useCtx(); const [status, setStatus] = useState<"" | WorldStatus>("");
  const query = useQuery({ queryKey: worldQueryKeys.list(ctx.workspaceCode, status), queryFn: () => worldApi.list(ctx, status), enabled: Boolean(ctx.apiKey) && !demo });
  return <div><WorldPageHeader title="生活世界" description="创建会持续发生故事的小世界，并邀请固定版本的 Agent 成为居民。" /><div className="mb-5 flex flex-wrap items-center gap-2"><div role="group" aria-label="世界状态筛选" className="flex flex-wrap gap-2">{FILTERS.map((item) => <button type="button" key={item.value} onClick={() => setStatus(item.value)} aria-pressed={status === item.value} className={status === item.value ? "button-primary" : "button-secondary"}>{item.label}</button>)}</div><Link href="/worlds/new" className="button-primary ml-auto"><Plus size={17} />创建世界</Link></div>{demo ? <div className="panel p-8 text-center"><h2 className="font-semibold">Demo 模式不提供生活世界假数据</h2><p className="mt-2 text-sm text-text-muted">切换到 live 模式并连接经授权的本地服务后使用。</p></div> : query.isLoading ? <div className="panel p-8" aria-busy="true"><span className="sr-only">正在加载世界列表</span><div aria-hidden="true" className="space-y-3">{Array.from({ length: 5 }, (_, i) => <div key={i} className="h-20 rounded-lg bg-subtle" />)}</div></div> : query.isError ? <WorldErrorNotice error={query.error} onRetry={() => void query.refetch()} /> : !query.data?.items.length ? <div className="panel grid min-h-80 place-items-center p-8 text-center"><div><Sparkle size={36} className="mx-auto text-primary" /><h2 className="mt-3 font-semibold">还没有生活世界</h2><p className="mt-2 text-sm text-text-muted">先创建一个会继续发生故事的小世界。</p><Link href="/worlds/new" className="button-primary mt-5">创建世界</Link></div></div> : <><div className="grid gap-3" aria-busy={query.isFetching}>{query.data.items.map((world) => <Link key={world.world_code} href={`/worlds/${world.world_code}`} className="panel grid min-h-24 gap-3 p-5 hover:border-primary/40 md:grid-cols-[minmax(0,1fr)_auto_auto] md:items-center"><div className="min-w-0"><h2 className="truncate font-semibold">{world.title || "未命名世界"}</h2><p className="mt-1 font-mono text-xs text-text-muted">{world.world_code} · revision {world.revision}</p></div><div className="text-sm text-text-muted">居民 {world.active_residents}/{world.total_residents}</div><WorldStatusBadge status={world.status} /></Link>)}</div>{query.isFetching && <p role="status" className="mt-3 text-sm text-text-muted">正在更新；当前显示上次结果。</p>}</>}</div>;
}

export function NewWorldWorkspace() {
  const router = useRouter(); const { ctx, demo } = useCtx(); const [worldCode, setWorldCode] = useState(""); const [title, setTitle] = useState(""); const [busy, setBusy] = useState(false); const [error, setError] = useUiError();
  const operationKey = useRef("");
  async function create() { if (!worldCode.trim() || !title.trim() || demo) return; setBusy(true); setError(undefined); operationKey.current ||= newIdempotencyKey("world-create"); try { const content = createEmptyWorldContent(); content.title = title.trim(); const world = await worldApi.create(ctx, { world_code: worldCode.trim().toLowerCase(), workspace_code: ctx.workspaceCode, content, idempotency_key: operationKey.current }); operationKey.current = ""; router.push(`/worlds/${world.world_code}/edit`); } catch (next) { setError(next); } finally { setBusy(false); } }
  return <div><WorldPageHeader title="创建生活世界" description="从空白开始，或先浏览经审核的平台模板。每次创建都会生成新的 world_code。" back="/worlds" /><div className="grid gap-5 lg:grid-cols-2"><section className="panel p-6"><h2 className="text-lg font-semibold">从空白开始</h2><label className="mt-5 block text-sm font-medium">世界标识<input value={worldCode} onChange={(e) => setWorldCode(e.target.value)} className="control-field mt-2 w-full" placeholder="monster-apartment" /></label><label className="mt-4 block text-sm font-medium">世界名称<input value={title} onChange={(e) => setTitle(e.target.value)} className="control-field mt-2 w-full" /></label>{error && <div className="mt-4"><WorldErrorNotice error={error} /></div>}<button type="button" onClick={() => void create()} disabled={busy || demo || !worldCode.trim() || !title.trim()} className="button-primary mt-5 min-h-11">{busy ? "正在创建…" : "创建草稿"}</button></section><Link href="/worlds/templates" className="panel p-6 hover:border-primary/40"><Sparkle size={26} className="text-primary" /><h2 className="mt-4 text-lg font-semibold">使用平台模板</h2><p className="mt-2 text-sm leading-6 text-text-muted">预览审核通过的模板内容；不会复制实例、居民、历史或检查点。</p><span className="button-secondary mt-5">浏览模板</span></Link></div></div>;
}

export function TemplatesWorkspace() {
  const router = useRouter(); const { ctx, demo } = useCtx(); const [busy, setBusy] = useState(""); const [error, setError] = useUiError();
  const operationKey = useRef("");
  const query = useQuery({ queryKey: worldQueryKeys.templates(ctx.workspaceCode), queryFn: () => worldApi.templates(ctx), enabled: Boolean(ctx.apiKey) && !demo });
  async function useTemplate(item: WorldTemplate) { setBusy(item.template_code); setError(undefined); operationKey.current ||= newIdempotencyKey(`world-template-${item.template_code}-${item.version_no}`); try { const world = await worldApi.create(ctx, { workspace_code: ctx.workspaceCode, content: item.content || createEmptyWorldContent(), template_code: item.template_code, template_version: item.version_no, idempotency_key: operationKey.current }); operationKey.current = ""; router.push(`/worlds/${world.world_code}/edit`); } catch (next) { setError(next); } finally { setBusy(""); } }
  // eslint-disable-next-line react-hooks/rules-of-hooks -- this is a backend action, not a Hook
  return <div><WorldPageHeader title="平台世界模板" description="只展示服务端审核并发布的模板；使用模板会创建全新草稿。" back="/worlds/new" />{error && <div className="mb-4"><WorldErrorNotice error={error} onRetry={() => void query.refetch()} /></div>}{query.isLoading ? <div className="panel p-8" aria-busy="true">正在加载模板…</div> : query.isError ? <WorldErrorNotice error={query.error} onRetry={() => void query.refetch()} /> : !query.data?.items.length ? <div className="panel p-8 text-center"><h2 className="font-semibold">暂时没有可用模板</h2><p className="mt-2 text-sm text-text-muted">你仍可从空白开始。</p><Link className="button-primary mt-5" href="/worlds/new">从空白开始</Link></div> : <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{query.data.items.map((item) => <article className="panel p-5" key={`${item.template_code}@${item.version_no}`}><span className="text-xs text-text-muted">模板 v{item.version_no}</span><h2 className="mt-2 font-semibold">{item.title}</h2><p className="mt-2 min-h-12 text-sm text-text-muted">{item.summary}</p><button className="button-primary mt-5 min-h-11" disabled={Boolean(busy)} onClick={() => void useTemplate(item)}>{busy === item.template_code ? "正在创建…" : "使用此模板"}</button></article>)}</div>}</div>;
}
