import { CheckCircle, Clock, FileText, LockKey, PencilSimple, ShieldCheck, Tag } from "@phosphor-icons/react";
import { SourceBadge } from "@/shared/ui/source-badge";
import type { PromptScope, SharedSessionRow } from "./types";

export function SessionInspector({ row, demo, onPrompt }: { row: SharedSessionRow | null; demo: boolean; onPrompt: (scope: PromptScope) => void }) {
  if (!row) return <aside className="border-t border-border p-5 text-sm text-text-muted min-[1400px]:border-l min-[1400px]:border-t-0">选择会话查看处理面板</aside>;
  const duration = Math.max(1, Math.round((new Date(row.session.updated_at).getTime() - new Date(row.session.created_at).getTime()) / 60000));
  return (
    <aside className="border-t border-border bg-surface p-5 min-[1400px]:border-l min-[1400px]:border-t-0">
      <div className="flex items-center justify-between"><h2 className="font-semibold">处理面板</h2><SourceBadge source={demo ? "demo" : "live"} /></div>
      <div className="mt-4 flex gap-2 rounded-lg border border-orange-200 bg-orange-50 px-3 py-3 text-xs leading-5 text-orange-900"><LockKey size={18} className="mt-0.5 shrink-0" />完整对话仅对已授权的工作空间角色可见。</div>
      <section className="mt-5 border-b border-border pb-5"><div className="flex items-center justify-between"><h3 className="text-sm font-semibold">会话状态</h3><span className="flex items-center gap-1 text-xs text-success"><span className="h-2 w-2 rounded-full bg-success" />{row.session.status === "review" ? "需复核" : "正常"}</span></div><dl className="mt-3 space-y-2 text-xs"><div className="flex justify-between"><dt className="text-text-muted">消息数</dt><dd>{row.session.message_count} 条</dd></div><div className="flex justify-between"><dt className="text-text-muted">Token</dt><dd>{row.session.total_tokens}</dd></div><div className="flex justify-between"><dt className="text-text-muted">会话时长</dt><dd>{duration} 分钟</dd></div></dl></section>
      <section className="border-b border-border py-5"><div className="flex items-center gap-2"><Tag size={17} className="text-primary" /><h3 className="text-sm font-semibold">质量标签</h3></div><div className="mt-3 flex flex-wrap gap-2"><span className="status-badge bg-blue-50 text-blue-700">信息更新</span>{row.session.verified && <span className="status-badge bg-emerald-50 text-emerald-700">已认证</span>}<span className="status-badge bg-slate-100 text-slate-600">共享会话</span></div></section>
      <section className="border-b border-border py-5"><h3 className="text-sm font-semibold">Prompt 补丁</h3><button type="button" onClick={() => onPrompt("session")} className="mt-3 flex w-full items-center gap-3 rounded-lg border border-border px-3 py-3 text-left hover:border-primary/50"><FileText size={19} className="text-primary" /><span className="flex-1"><strong className="block text-sm">会话级 Prompt</strong><span className="text-xs text-text-muted">仅当前会话生效</span></span><PencilSimple size={16} /></button><button type="button" onClick={() => onPrompt("user")} className="mt-2 flex w-full items-center gap-3 rounded-lg border border-border px-3 py-3 text-left hover:border-primary/50"><ShieldCheck size={19} className="text-primary" /><span className="flex-1"><strong className="block text-sm">用户级 Prompt</strong><span className="text-xs text-text-muted">该用户所有会话生效</span></span><PencilSimple size={16} /></button></section>
      <section className="py-5"><h3 className="text-sm font-semibold">权限记录</h3><div className="mt-3 space-y-3 text-xs"><p className="flex gap-2"><Clock size={16} className="shrink-0 text-text-muted" /><span><b>系统</b> · 共享会话授权已确认<br /><span className="text-text-muted">{new Date(row.session.updated_at).toLocaleString("zh-CN", { hour12: false })}</span></span></p>{row.session.verified && <p className="flex gap-2"><CheckCircle size={16} className="shrink-0 text-success" /><span><b>创作者</b> · 标记为已认证</span></p>}</div></section>
    </aside>
  );
}
